# Generated by Django 2.2.2 on 2019-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20190612_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(through='classroom.TakenQuiz', to='classroom.Quiz'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='status',
            field=models.CharField(default='Incomplete', max_length=12),
        ),
    ]
