# Generated by Django 2.1.7 on 2019-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20190527_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='status',
            field=models.CharField(default='Enrolled', max_length=12),
        ),
    ]
