# Generated by Django 2.2.2 on 2019-06-18 14:57

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20190615_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='takencourse',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='status',
            field=models.CharField(default='incomplete', max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profile_pics/default-user.png', upload_to='profile_pics'),
        ),
    ]
