# Generated by Django 2.1.7 on 2019-05-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_takencourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='status',
            field=models.CharField(default='Pending', max_length=12),
        ),
    ]
