# Generated by Django 2.1.7 on 2019-05-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20190529_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classroom.Subject'),
        ),
    ]
