# Generated by Django 2.2.2 on 2019-06-18 15:45

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20190618_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profile_pics/default-user.png', upload_to='profile_pics'),
        ),
    ]
