# Generated by Django 2.2.2 on 2019-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_auto_20190622_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
    ]
