# Generated by Django 2.2.2 on 2019-06-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20190623_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='course',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='classroom.Course'),
        ),
    ]
