# Generated by Django 2.2.2 on 2019-06-26 03:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_takenquiz_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(help_text='Recommended image resolution: 740px x 480px', upload_to='courses'),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='classroom.Course'),
        ),
    ]
