# Generated by Django 2.2.2 on 2019-07-02 11:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_auto_20190627_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profile_pics/default-user.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profile_pics/default-user.jpg', upload_to='profile_pics'),
        ),
    ]
