# Generated by Django 2.2.2 on 2019-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_auto_20190825_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='file',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
